web_application:
  image: centos/httpd 
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - /var/log/centos-web:/var/log/httpd
db:
  image: astondevops/docker-mysql-5.6 
  environment:
    MYSQL_ROOT_PASSWORD: password
  volumes: 
    - /var/log/mysql-db:/var/log/mysql
phpmyadmin:
  image: nazarpc/phpmyadmin
  links:
    - db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: password 

