---

- hosts: all
  become: true
  become_user: centos
  vars_files:
    - vars/main.yml
  tasks:
    - name: Install require packages 
      become: true
      become_user: root
      yum: name={{item}} state=present update_cache=yes
      with_items:
        - git 
        - wget
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: Add docker repo
      become_user: root
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Add ce edge
      become_user: root
      command:  yum-config-manager --enable docker-ce-edge
    - name: Add ce test
      become_user: root
      command:  yum-config-manager --enable docker-ce-test
    - name: Add docker package
      become_user: root
      yum: name=docker-ce state=present update_cache=yes
    - name: set docker daemon 
      become_user: root
      command: systemctl enable docker
    - name: start docker daemon 
      become_user: root
      command: systemctl start docker
    - name: set default user in docker group 
      become_user: root
      command: usermod -aG docker centos 
    - name: Install epel 
      become_user: root
      yum: name=epel-release state=present update_cache=yes
    - name: install python pip
      become_user: root
      yum: name=python-pip state=present update_cache=yes 
    - name: Install docker compose
      become_user: root
      command:  pip install docker-compose
    - name: Install pyopenssl and other
      become_user: root
      command:  pip install pyopenssl ndg-httpsclient pyasn1
    - name: Update urllib3
      become_user: root
      command: pip install -U urllib3
    - name: set python aws path 
      stat: path=/home/centos/python2-aws
      register: check_path 
    - name: Print path
      debug: msg="Path = {{ check_path.stat.exists }} "
    - name: Get the git repository 
      command: git clone https://github.com/promogekko/python2-aws.git
      when: not check_path.stat.exists
    - name: pull existing repository
      command: chdir=/home/centos/python2-aws git pull
      when: check_path.stat.exists == True
    - name: do docker-compose
      become_user: root
      command: chdir=/home/centos/python2-aws docker-compose up -d 
    - include: tasks/main.yml
    - name: Install python boto3
      become_user: root
      command: pip install boto3
    - name: run copy logfiles to S3
      command: /home/centos/python2-aws/log2S3.py
    - name: Copy the .netrc conf file
      copy:
        dest: "/home/centos/.netrc"
        owner: centos
        mode: 0600 # needed since it contains a password
        content: |
             machine db 
             login root
             password password
      become_user: centos
    - name: run backup database test to S3
      command: /home/centos/python2-aws/mysql-backup.py
